const initState = {
  user: {},
  inputSignup: {},
  inputSignin: {},
  posts: [],
  post: { loading: true },
  excursions: [],
  excursion: { loading: true },
  cart: [],
  commentsExcursions: [],
  commentsPosts: [],
  showSignUp: false,
  showSignIn: false,
  showCart: false,
  showPost: false,
  showOrderModal: false,
  showExcursion: false,
  allCount: 0,
  allPrice: 0,
  yandexMaps: {},
  arrYandexMap: [],
  placemarks: [],
  personalOrder: [],
};

export default initState;
